import Head from "next/head";

//Styles
import { HomeStyles } from "../styles/home";

import RSVPForm from "../components/RSVPForm";

export default function Home() {
  return (
    <div className="websiteContainer">
      <HomeStyles />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bgImage">
        <div className="gradient"></div>
        <img src="/images/Background.jpg" className="bgImg" />
      </div>
      <div className="container-fluid contentContainer">
        <div className="row">
          <div className="col-12">
            <h1>
              Thomas Bye
              <br />&<br />
              Katelyn Leddy
            </h1>
            <hr />
            <h2>August 28th 2022</h2>
            <div className="rsvpButton">RSVP</div>
          </div>
        </div>
      </div>
      <div className="container-fluid rsvpContainer">
        <div className="row">
          <div className="col-12">
            <RSVPForm />
          </div>
        </div>
      </div>

      <footer></footer>
    </div>
  );
}
