import Head from "next/head";
import React, { useEffect } from "react";
import axios from "axios";
import DataTable, { createTheme } from "react-data-table-component";

const columns = [
  {
    name: "Name",
    selector: "name1",
    sortable: true,
  },
  {
    name: "Meal",
    sortable: true,
    selector: "meal1",
  },
  {
    name: "Name 2",
    sortable: true,
    selector: "name2",
  },
  {
    name: "Meal 2",
    selector: "meal2",
    sortable: true,
  },
  {
    name: "Dietary",
    selector: "dietary",
    sortable: true,
  },
];

createTheme("solarized", {
  text: {
    primary: "black",
    secondary: "blue",
  },
  background: {
    default: "white",
  },
  striped: {
    default: "white",
    primary: "white",
    text: {
      primary: "white",
    },
  },
  context: {
    background: "#CCC",
    text: "#FFFFFF",
  },
  divider: {
    default: "#d2263a",
  },
  action: {
    button: "red",
    hover: "red",
    disabled: "red",
  },
  highlightOnHover: {
    default: "#d2263a",
    text: "white",
  },
});

//Styles
import { HomeStyles } from "../styles/home";

export default function Rsvpers(props) {
  useEffect(() => {});

  return (
    <div className="websiteContainer">
      <HomeStyles />
      <Head>
        <title>Thomas & Katelyn&apos;s Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid contentContainer">
        <div className="row">
          <div className="col-12">
            <DataTable
              keyField="name1"
              striped={true}
              columns={columns}
              data={props.myRsvp}
              theme="solarized"
              highlightOnHover={true}
              dense={true}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

Rsvpers.getInitialProps = async (ctx) => {
  const defaultProps = {
    responseMessage: "Something went wrong, please try again",
    responseAlert: "danger",
    initFail: true,
  };
  const props = await axios
    .post("https://thomasandkatelyn.com/api/getrsvp", {})
    .then((res) => {
      //pass response to UI
      console.log(res.data.payload);
      if (res.data.response.boolean) {
        return {
          myRsvp: res.data.payload,
        };
      }
    })
    .catch((e) => {
      console.log(e);
      //Not Found
      return defaultProps;
    });
  return props;
};
